services:
    netbull_media.form.type.file:
        class: NetBull\MediaBundle\Form\Type\FileType
        tags:
            - { name: form.type }
        arguments: ['@netbull_media.pool']

    netbull_media.form.type.photo:
        class: NetBull\MediaBundle\Form\Type\PhotoType
        tags:
            - { name: form.type }
        arguments: ['@netbull_media.pool']

    netbull_media.form.type.short.media:
        class: NetBull\MediaBundle\Form\Type\MediaShortType
        tags:
            - { name: form.type }
        arguments: ['@netbull_media.pool']

    netbull_media.form.type.media:
        class: NetBull\MediaBundle\Form\Type\MediaType
        tags:
            - { name: form.type }
        arguments: ['@netbull_media.pool']

    netbull_media.form.type.media.dynamic:
        class: NetBull\MediaBundle\Form\Type\MediaDynamicType
        tags:
            - { name: form.type }
        arguments: ['@netbull_media.pool']