services:
    netbull_media.helper.path:
        class: NetBull\MediaBundle\Helpers\PathGenerator
        arguments: ['@netbull_media.pool', '@?twig']
        public: true

    NetBull\MediaBundle\Helpers\PathGenerator:
        alias: netbull_media.helper.path
