services:
    NetBull\MediaBundle\Form\Type\:
        resource: '../../Form/Type/*'
        exclude: '../../Form/Type/BaseType.php'
        tags:
            - { name: form.type }
        arguments: ['@NetBull\MediaBundle\Provider\Pool']
