services:
    NetBull\MediaBundle\EventListener\MediaListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'postRemove' }
            - { name: 'doctrine.event_listener', event: 'postFlush' }
        arguments: [ '@NetBull\MediaBundle\Provider\Pool' ]
