services:
    NetBull\MediaBundle\Provider\Pool:
        arguments: ['']
        public: true

    NetBull\MediaBundle\Thumbnail\FormatThumbnail:
        arguments: ['@parameter_bag', '@logger']

    netbull_media.provider.image:
        class: NetBull\MediaBundle\Provider\ImageProvider
        tags:
            - { name: netbull_media.provider }
        arguments: ['netbull_media.provider.image', '', '', '@NetBull\MediaBundle\Thumbnail\FormatThumbnail', '@router', '@NetBull\MediaBundle\Signature\SimpleSignatureHasher', '', '', '', '@netbull_media.metadata.amazon']
        calls:
            - [setTemplates, [{ helper_thumbnail: 'NetBullMedia/Provider/thumbnail.html.twig', helper_view: '\NetBullMedia/Provider/view_image.html.twig' }]]

    netbull_media.provider.file:
        class: NetBull\MediaBundle\Provider\FileProvider
        tags:
            - { name: netbull_media.provider }
        arguments: ['netbull_media.provider.file', '', '', '@NetBull\MediaBundle\Thumbnail\FormatThumbnail', '@router', '@NetBull\MediaBundle\Signature\SimpleSignatureHasher', '', '', '@netbull_media.metadata.amazon']
        calls:
            - [setTemplates, [{ helper_thumbnail: 'NetBullMedia/Provider/thumbnail.html.twig', helper_view: 'NetBullMedia/Provider/view_file.html.twig' }]]

    netbull_media.provider.youtube:
        class: NetBull\MediaBundle\Provider\YouTubeProvider
        tags:
            - { name: netbull_media.provider }
        arguments: ['netbull_media.provider.youtube', '', '', '@NetBull\MediaBundle\Thumbnail\FormatThumbnail', '@netbull_media.metadata.amazon', '']
        calls:
            - [setTemplates, [{ helper_thumbnail: 'NetBullMedia/Provider/thumbnail.html.twig', helper_view: 'NetBullMedia/Provider/view_youtube.html.twig' }]]

    netbull_media.provider.vimeo:
        class: NetBull\MediaBundle\Provider\VimeoProvider
        tags:
            - { name: netbull_media.provider }
        arguments: ['netbull_media.provider.vimeo', '', '', '@NetBull\MediaBundle\Thumbnail\FormatThumbnail', '@netbull_media.metadata.amazon']
        calls:
            - [setTemplates, [{ helper_thumbnail: 'NetBullMedia/Provider/thumbnail.html.twig', helper_view: 'NetBullMedia/Provider/view_vimeo.html.twig' }]]

    netbull_media.provider.youku:
        class: NetBull\MediaBundle\Provider\YoukuProvider
        tags:
            - { name: netbull_media.provider }
        arguments: ['netbull_media.provider.youku', '', '', '@NetBull\MediaBundle\Thumbnail\FormatThumbnail', '@netbull_media.metadata.amazon']
        calls:
            - [setTemplates, [{ helper_thumbnail: 'NetBullMedia/Provider/thumbnail.html.twig', helper_view: 'NetBullMedia/Provider/view_youku.html.twig' }]]
